// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

import "github.com/JavierZunzunegui/Go2_error_values_feedback/xerrors"

// compile time check the provided type implements error
var _ error = (Foorer)(nil)

func isFoorer(err error) bool {
	_, ok := err.(Foorer)
	return ok
}

func LastFoorer(err error) Foorer {
	lastErr := xerrors.Last(err, isFoorer)
	if lastErr == nil {
		return nil
	}
	return lastErr.(Foorer)
}
